In [ ]:
import numpy as np

In [1]:
import torch
print(torch.__version__) # torch 버전
print(torch.version.cuda) # cuda 버전

2.4.1+cpu
None


In [4]:
import torch
import torch.nn as nn

# Bilinear 계층 정의
bilinear = nn.Bilinear(in1_features=5, in2_features=10, out_features=3)

# 입력 텐서 생성
x1 = torch.randn(4, 5)  # 첫 번째 입력 (배치 크기: 4, 특징 차원: 5)
x2 = torch.randn(4, 10) # 두 번째 입력 (배치 크기: 4, 특징 차원: 10)

# 빌리니어 연산 수행
output = bilinear(x1, x2)
print(x1)
print(output.shape)  # torch.Size([4, 3])

tensor([[ 0.3889,  0.0903,  0.3355,  1.4204, -1.2362],
        [ 1.0803,  0.6316,  0.0809, -0.4822, -0.3039],
        [ 2.7431, -0.7746, -2.1266, -0.4472,  0.8016],
        [ 0.6726, -1.5422,  0.5993, -0.8714,  0.3406]])
torch.Size([4, 3])


In [5]:
B = nn.Bilinear(2, 2, 1)
print(B.weight)

Parameter containing:
tensor([[[-0.5852,  0.2958],
         [-0.2399, -0.6740]]], requires_grad=True)


In [7]:
print(B(torch.ones(2), torch.zeros(2)))
print(B(torch.zeros(2), torch.ones(2)))

tensor([0.5216], grad_fn=<AddBackward0>)
tensor([0.5216], grad_fn=<AddBackward0>)


In [14]:
B = nn.Bilinear(2, 2, 1, bias=False)
A = B.weight
print(A)
print(dir(B))
# None

Parameter containing:
tensor([[[-0.3297, -0.3921],
         [ 0.0159,  0.2201]]], requires_grad=True)
['T_destination', '__annotations__', '__call__', '__class__', '__constants__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_backward_hooks', '_backward_pre_hooks', '_buffers', '_call_impl', '_compiled_call_impl', '_forward_hooks', '_forward_hooks_always_called', '_forward_hooks_with_kwargs', '_forward_pre_hooks', '_forward_pre_hooks_with_kwargs', '_get_backward_hooks', '_get_backward_pre_hooks', '_get_name', '_is_full_backward_hook', '_load_from_state_dict', '_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_maybe_warn_non_full_backwar

In [26]:
b = torch.zeros((3,1))
b

tensor([[0.],
        [0.],
        [0.]])

In [ ]:

b = torch.zeros(1)

print(B(x_ones, x_zeros))
# > tensor([0.], grad_fn=<ThAddBackward>)
print(manual_bilinear(x_ones.view(1, 2), x_zeros.view(2, 1), A.squeeze(), b))
# > tensor([0.], grad_fn=<ThAddBackward>)

print(B(x_ones, x_ones))
# > tensor([-0.7897], grad_fn=<ThAddBackward>)
print(manual_bilinear(x_ones.view(1, 2), x_ones.view(2, 1), A.squeeze(), b))
# > tensor([[-0.7897]], grad_fn=<ThAddBackward>)

In [1]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


In [2]:
print(torch.__version__) # torch 버전
print(torch.version.cuda) # cuda 버전

2.4.1+cu121
12.1


In [5]:
esol = ['MinEStateIndex', 'MinPartialCharge', 'MinAbsPartialCharge', 'FpDensityMorgan1', 'FpDensityMorgan2',
        'FpDensityMorgan3', 'BCUT2D_CHGHI', 'SMR_VSA5', 'SlogP_VSA2', 'SlogP_VSA5', 'SlogP_VSA6', 'SlogP_VSA8',
        'EState_VSA9', 'VSA_EState7', 'HeavyAtomCount', 'NumAromaticHeterocycles', 'NumHAcceptors', 'RingCount',
        'MolMR', 'fr_C_O_noCOO']
logvp = ['qed', 'MolWt', 'Kappa2', 'PEOE_VSA12', 'SlogP_VSA1', 'TPSA', 'EState_VSA1', 'EState_VSA10', 'VSA_EState1',
         'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'NumAliphaticRings', 'NumSaturatedRings', 'fr_Ar_NH',
         'fr_COO2', 'fr_azo', 'fr_benzene', 'fr_methoxy', 'fr_pyridine']

set(esol) & set(logvp)

{'HeavyAtomCount'}