In [ ]:
import numpy as np

In [1]:
import torch
print(torch.__version__) # torch 버전
print(torch.version.cuda) # cuda 버전

2.4.1+cpu
None


In [4]:
import torch
import torch.nn as nn

# Bilinear 계층 정의
bilinear = nn.Bilinear(in1_features=5, in2_features=10, out_features=3)

# 입력 텐서 생성
x1 = torch.randn(4, 5)  # 첫 번째 입력 (배치 크기: 4, 특징 차원: 5)
x2 = torch.randn(4, 10) # 두 번째 입력 (배치 크기: 4, 특징 차원: 10)

# 빌리니어 연산 수행
output = bilinear(x1, x2)
print(x1)
print(output.shape)  # torch.Size([4, 3])

tensor([[ 0.3889,  0.0903,  0.3355,  1.4204, -1.2362],
        [ 1.0803,  0.6316,  0.0809, -0.4822, -0.3039],
        [ 2.7431, -0.7746, -2.1266, -0.4472,  0.8016],
        [ 0.6726, -1.5422,  0.5993, -0.8714,  0.3406]])
torch.Size([4, 3])


In [5]:
B = nn.Bilinear(2, 2, 1)
print(B.weight)

Parameter containing:
tensor([[[-0.5852,  0.2958],
         [-0.2399, -0.6740]]], requires_grad=True)


In [7]:
print(B(torch.ones(2), torch.zeros(2)))
print(B(torch.zeros(2), torch.ones(2)))

tensor([0.5216], grad_fn=<AddBackward0>)
tensor([0.5216], grad_fn=<AddBackward0>)


In [14]:
B = nn.Bilinear(2, 2, 1, bias=False)
A = B.weight
print(A)
print(dir(B))
# None

Parameter containing:
tensor([[[-0.3297, -0.3921],
         [ 0.0159,  0.2201]]], requires_grad=True)
['T_destination', '__annotations__', '__call__', '__class__', '__constants__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_backward_hooks', '_backward_pre_hooks', '_buffers', '_call_impl', '_compiled_call_impl', '_forward_hooks', '_forward_hooks_always_called', '_forward_hooks_with_kwargs', '_forward_pre_hooks', '_forward_pre_hooks_with_kwargs', '_get_backward_hooks', '_get_backward_pre_hooks', '_get_name', '_is_full_backward_hook', '_load_from_state_dict', '_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_maybe_warn_non_full_backwar

In [26]:
b = torch.zeros((3,1))
b

tensor([[0.],
        [0.],
        [0.]])

In [ ]:

b = torch.zeros(1)

print(B(x_ones, x_zeros))
# > tensor([0.], grad_fn=<ThAddBackward>)
print(manual_bilinear(x_ones.view(1, 2), x_zeros.view(2, 1), A.squeeze(), b))
# > tensor([0.], grad_fn=<ThAddBackward>)

print(B(x_ones, x_ones))
# > tensor([-0.7897], grad_fn=<ThAddBackward>)
print(manual_bilinear(x_ones.view(1, 2), x_ones.view(2, 1), A.squeeze(), b))
# > tensor([[-0.7897]], grad_fn=<ThAddBackward>)

In [1]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


In [2]:
print(torch.__version__) # torch 버전
print(torch.version.cuda) # cuda 버전

2.4.1+cu121
12.1


In [5]:
esol = ['MinEStateIndex', 'MinPartialCharge', 'MinAbsPartialCharge', 'FpDensityMorgan1', 'FpDensityMorgan2',
        'FpDensityMorgan3', 'BCUT2D_CHGHI', 'SMR_VSA5', 'SlogP_VSA2', 'SlogP_VSA5', 'SlogP_VSA6', 'SlogP_VSA8',
        'EState_VSA9', 'VSA_EState7', 'HeavyAtomCount', 'NumAromaticHeterocycles', 'NumHAcceptors', 'RingCount',
        'MolMR', 'fr_C_O_noCOO']
logvp = ['qed', 'MolWt', 'Kappa2', 'PEOE_VSA12', 'SlogP_VSA1', 'TPSA', 'EState_VSA1', 'EState_VSA10', 'VSA_EState1',
         'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'NumAliphaticRings', 'NumSaturatedRings', 'fr_Ar_NH',
         'fr_COO2', 'fr_azo', 'fr_benzene', 'fr_methoxy', 'fr_pyridine']

set(esol) & set(logvp)

{'HeavyAtomCount'}

In [1]:
a = ['MinPartialCharge', 'FpDensityMorgan1', 'FpDensityMorgan3', 'SMR_VSA5', 'SlogP_VSA2', 'SlogP_VSA6', 'HeavyAtomCount', 'NumHAcceptors', 'RingCount', 'MolMR']
b = ['MinEStateIndex', 'MinPartialCharge', 'MinAbsPartialCharge', 'FpDensityMorgan1', 'FpDensityMorgan2', 'FpDensityMorgan3', 'BCUT2D_CHGHI', 'SMR_VSA5', 'SlogP_VSA2', 'SlogP_VSA5', 'SlogP_VSA6', 'SlogP_VSA8', 'EState_VSA9', 'VSA_EState7', 'HeavyAtomCount', 'NumAromaticHeterocycles', 'NumHAcceptors', 'RingCount', 'MolMR', 'fr_C_O_noCOO']
set(b) - set(a)

{'BCUT2D_CHGHI',
 'EState_VSA9',
 'FpDensityMorgan2',
 'MinAbsPartialCharge',
 'MinEStateIndex',
 'NumAromaticHeterocycles',
 'SlogP_VSA5',
 'SlogP_VSA8',
 'VSA_EState7',
 'fr_C_O_noCOO'}

In [ ]:
# logvp
a_3 = ['TPSA', 'EState_VSA10', 'HeavyAtomCount']
a_5 = ['TPSA', 'EState_VSA10', 'VSA_EState8', 'HeavyAtomCount', 'fr_benzene']

a_7 = ['TPSA', 'EState_VSA10', 'VSA_EState1', 'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'fr_benzene']
a_10 = ['MolWt', 'TPSA', 'EState_VSA1', 'EState_VSA10', 'VSA_EState1', 'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'fr_COO2', 'fr_benzene']
a_20 = ['qed', 'MolWt', 'Kappa2', 'PEOE_VSA12', 'SlogP_VSA1', 'TPSA', 'EState_VSA1', 'EState_VSA10', 'VSA_EState1', 'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'NumAliphaticRings', 'NumSaturatedRings', 'fr_Ar_NH', 'fr_COO2', 'fr_azo', 'fr_benzene', 'fr_methoxy', 'fr_pyridine']

print(set(a_5) - set(a_3), '\n')
print(set(a_7) - set(a_5), '\n')
print(set(a_10) - set(a_7), '\n')
print(set(a_20) - set(a_10))


{'fr_benzene', 'VSA_EState8'} 

{'VSA_EState6', 'VSA_EState1'} 

{'fr_COO2', 'MolWt', 'EState_VSA1'} 

{'fr_pyridine', 'PEOE_VSA12', 'qed', 'fr_methoxy', 'fr_azo', 'SlogP_VSA1', 'NumSaturatedRings', 'fr_Ar_NH', 'Kappa2', 'NumAliphaticRings'}


In [2]:
import pandas as pd
import numpy as np
qm7 = pd.read_csv('C:\Programming\Github\EGCN\data\qm7.csv')
qm7

smiles   u0_atom
0                                   C([H])([H])([H])[H]  5.055745
1                          [H]C([H])([H])C([H])([H])[H]  3.734646
2                                   [H]C([H])=C([H])[H]  4.399592
3                                             [H]C#C[H]  5.114429
4                         [H]OC([H])([H])C([H])([H])[H]  3.301922
...                                                 ...       ...
6825  [H]C(=C(C#N)C([H])([H])[H])C([H])([H])C([H])([... -1.681114
6826  [H]C(=C([H])C([H])(N([H])[H])C([H])([H])[H])C(... -0.506051
6827  [H]C(=C([H])C([H])([H])C([H])([H])[H])C([H])([... -0.526106
6828  [H]C([H])=C(C([H])([H])C([H])([H])[H])C([H])([... -1.064084
6829  [H]C([H])=C(C([H])([H])C([H])([H])[H])C([H])(N... -1.678692

[6830 rows x 2 columns]

In [19]:
qm7_reduced = qm7.iloc[np.random.randint(0, len(qm7), 2000)].reset_index(drop=True)
qm7_reduced

smiles   u0_atom
0     [H]OC([H])([H])C([H])([H])C([H])([H])N([H])C([... -0.088626
1     [H]C([H])([H])N(C([H])([H])[H])C1([H])C([H])([... -0.291058
2     [H]C1([H])N2C3([H])C([H])([H])C([H])(C3([H])[H... -0.306760
3      [H]N1C(=O)N([H])C([H])([H])C([H])([H])C1([H])[H]  0.761837
4         [H]C#CC([H])([H])C([H])(O[H])C([H])=C([H])[H] -0.015810
...                                                 ...       ...
1995           [H]C1([H])OC2([H])C(=O)C1([H])C2([H])[H]  0.801767
1996                         [H]C#CC(=O)C([H])([H])O[H]  2.138434
1997              [H]ON1N=C([H])C(=C1[H])C([H])([H])[H]  1.036636
1998        [H]C#CC([H])([H])C([H])(O[H])C([H])([H])[H]  0.661698
1999  [H]OC([H])([H])C([H])=C([H])C1([H])N([H])C1([H...  0.596375

[2000 rows x 2 columns]

In [20]:
qm7_reduced.to_csv('qm7_reduced.csv', index = False)


In [23]:
# qm7
qm7_3 = ['Chi0v', 'Chi1n', 'Chi1v'] 
qm7_5 = ['MaxPartialCharge', 'Chi0v', 'Chi1n', 'Chi1v', 'Kappa2']
qm7_7 = ['MaxPartialCharge', 'Chi0v', 'Chi1n', 'Chi1v', 'Kappa2', 'SlogP_VSA4', 'EState_VSA9']
qm7_10 = ['MaxPartialCharge', 'Chi0v', 'Chi1n', 'Chi1v', 'Kappa2', 'PEOE_VSA4', 'SlogP_VSA3', 'SlogP_VSA4', 'EState_VSA9', 'VSA_EState2']
qm7_20 = ['MaxPartialCharge', 'BCUT2D_MRLOW', 'Chi0v', 'Chi1n', 'Chi1v', 'Kappa2', 'PEOE_VSA11', 'PEOE_VSA4', 'SMR_VSA5', 'SlogP_VSA3', 'SlogP_VSA4', 'SlogP_VSA8', 'EState_VSA7', 'EState_VSA9', 'VSA_EState2', 'VSA_EState7', 'fr_NH1', 'fr_Ndealkylation1', 'fr_epoxide']

print(set(qm7_3), '\n')
print(set(qm7_5) - set(qm7_3), '\n')
print(set(qm7_7) - set(qm7_5), '\n')
print(set(qm7_10) - set(qm7_7), '\n')
print(set(qm7_20) - set(qm7_10))


{'Chi1n', 'Chi1v', 'Chi0v'} 

{'MaxPartialCharge', 'Kappa2'} 

{'SlogP_VSA4', 'EState_VSA9'} 

{'VSA_EState2', 'PEOE_VSA4', 'SlogP_VSA3'} 

{'BCUT2D_MRLOW', 'PEOE_VSA11', 'SlogP_VSA8', 'EState_VSA7', 'fr_Ndealkylation1', 'SMR_VSA5', 'fr_epoxide', 'fr_NH1', 'VSA_EState7'}


In [25]:
len(set(qm7_10))

10