In [ ]:
import numpy as np

In [1]:
import torch
print(torch.__version__) # torch 버전
print(torch.version.cuda) # cuda 버전

2.4.1+cpu
None


In [4]:
import torch
import torch.nn as nn

# Bilinear 계층 정의
bilinear = nn.Bilinear(in1_features=5, in2_features=10, out_features=3)

# 입력 텐서 생성
x1 = torch.randn(4, 5)  # 첫 번째 입력 (배치 크기: 4, 특징 차원: 5)
x2 = torch.randn(4, 10) # 두 번째 입력 (배치 크기: 4, 특징 차원: 10)

# 빌리니어 연산 수행
output = bilinear(x1, x2)
print(x1)
print(output.shape)  # torch.Size([4, 3])

tensor([[ 0.3889,  0.0903,  0.3355,  1.4204, -1.2362],
        [ 1.0803,  0.6316,  0.0809, -0.4822, -0.3039],
        [ 2.7431, -0.7746, -2.1266, -0.4472,  0.8016],
        [ 0.6726, -1.5422,  0.5993, -0.8714,  0.3406]])
torch.Size([4, 3])


In [5]:
B = nn.Bilinear(2, 2, 1)
print(B.weight)

Parameter containing:
tensor([[[-0.5852,  0.2958],
         [-0.2399, -0.6740]]], requires_grad=True)


In [7]:
print(B(torch.ones(2), torch.zeros(2)))
print(B(torch.zeros(2), torch.ones(2)))

tensor([0.5216], grad_fn=<AddBackward0>)
tensor([0.5216], grad_fn=<AddBackward0>)


In [14]:
B = nn.Bilinear(2, 2, 1, bias=False)
A = B.weight
print(A)
print(dir(B))
# None

Parameter containing:
tensor([[[-0.3297, -0.3921],
         [ 0.0159,  0.2201]]], requires_grad=True)
['T_destination', '__annotations__', '__call__', '__class__', '__constants__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_backward_hooks', '_backward_pre_hooks', '_buffers', '_call_impl', '_compiled_call_impl', '_forward_hooks', '_forward_hooks_always_called', '_forward_hooks_with_kwargs', '_forward_pre_hooks', '_forward_pre_hooks_with_kwargs', '_get_backward_hooks', '_get_backward_pre_hooks', '_get_name', '_is_full_backward_hook', '_load_from_state_dict', '_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_maybe_warn_non_full_backwar

In [26]:
b = torch.zeros((3,1))
b

tensor([[0.],
        [0.],
        [0.]])

In [ ]:

b = torch.zeros(1)

print(B(x_ones, x_zeros))
# > tensor([0.], grad_fn=<ThAddBackward>)
print(manual_bilinear(x_ones.view(1, 2), x_zeros.view(2, 1), A.squeeze(), b))
# > tensor([0.], grad_fn=<ThAddBackward>)

print(B(x_ones, x_ones))
# > tensor([-0.7897], grad_fn=<ThAddBackward>)
print(manual_bilinear(x_ones.view(1, 2), x_ones.view(2, 1), A.squeeze(), b))
# > tensor([[-0.7897]], grad_fn=<ThAddBackward>)

In [1]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


In [2]:
print(torch.__version__) # torch 버전
print(torch.version.cuda) # cuda 버전

2.4.1+cu121
12.1


In [5]:
esol = ['MinEStateIndex', 'MinPartialCharge', 'MinAbsPartialCharge', 'FpDensityMorgan1', 'FpDensityMorgan2',
        'FpDensityMorgan3', 'BCUT2D_CHGHI', 'SMR_VSA5', 'SlogP_VSA2', 'SlogP_VSA5', 'SlogP_VSA6', 'SlogP_VSA8',
        'EState_VSA9', 'VSA_EState7', 'HeavyAtomCount', 'NumAromaticHeterocycles', 'NumHAcceptors', 'RingCount',
        'MolMR', 'fr_C_O_noCOO']
logvp = ['qed', 'MolWt', 'Kappa2', 'PEOE_VSA12', 'SlogP_VSA1', 'TPSA', 'EState_VSA1', 'EState_VSA10', 'VSA_EState1',
         'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'NumAliphaticRings', 'NumSaturatedRings', 'fr_Ar_NH',
         'fr_COO2', 'fr_azo', 'fr_benzene', 'fr_methoxy', 'fr_pyridine']

set(esol) & set(logvp)

{'HeavyAtomCount'}

In [1]:
a = ['MinPartialCharge', 'FpDensityMorgan1', 'FpDensityMorgan3', 'SMR_VSA5', 'SlogP_VSA2', 'SlogP_VSA6', 'HeavyAtomCount', 'NumHAcceptors', 'RingCount', 'MolMR']
b = ['MinEStateIndex', 'MinPartialCharge', 'MinAbsPartialCharge', 'FpDensityMorgan1', 'FpDensityMorgan2', 'FpDensityMorgan3', 'BCUT2D_CHGHI', 'SMR_VSA5', 'SlogP_VSA2', 'SlogP_VSA5', 'SlogP_VSA6', 'SlogP_VSA8', 'EState_VSA9', 'VSA_EState7', 'HeavyAtomCount', 'NumAromaticHeterocycles', 'NumHAcceptors', 'RingCount', 'MolMR', 'fr_C_O_noCOO']
set(b) - set(a)

{'BCUT2D_CHGHI',
 'EState_VSA9',
 'FpDensityMorgan2',
 'MinAbsPartialCharge',
 'MinEStateIndex',
 'NumAromaticHeterocycles',
 'SlogP_VSA5',
 'SlogP_VSA8',
 'VSA_EState7',
 'fr_C_O_noCOO'}

In [ ]:
# logvp
a_3 = ['TPSA', 'EState_VSA10', 'HeavyAtomCount']
a_5 = ['TPSA', 'EState_VSA10', 'VSA_EState8', 'HeavyAtomCount', 'fr_benzene']
a_7 = ['TPSA', 'EState_VSA10', 'VSA_EState1', 'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'fr_benzene']
a_10 = ['MolWt', 'TPSA', 'EState_VSA1', 'EState_VSA10', 'VSA_EState1', 'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'fr_COO2', 'fr_benzene']
a_20 = ['qed', 'MolWt', 'Kappa2', 'PEOE_VSA12', 'SlogP_VSA1', 'TPSA', 'EState_VSA1', 'EState_VSA10', 'VSA_EState1', 'VSA_EState6', 'VSA_EState8', 'HeavyAtomCount', 'NumAliphaticRings', 'NumSaturatedRings', 'fr_Ar_NH', 'fr_COO2', 'fr_azo', 'fr_benzene', 'fr_methoxy', 'fr_pyridine']

print(set(a_5) - set(a_3), '\n')
print(set(a_7) - set(a_5), '\n')
print(set(a_10) - set(a_7), '\n')
print(set(a_20) - set(a_10))

{'fr_benzene', 'VSA_EState8'} 

{'VSA_EState6', 'VSA_EState1'} 

{'fr_COO2', 'MolWt', 'EState_VSA1'} 

{'fr_pyridine', 'PEOE_VSA12', 'qed', 'fr_methoxy', 'fr_azo', 'SlogP_VSA1', 'NumSaturatedRings', 'fr_Ar_NH', 'Kappa2', 'NumAliphaticRings'}


In [ ]:
# qm7
qm7_3 = ['Chi0v', 'Chi1n', 'Chi1v'] 
qm7_5 = ['MaxPartialCharge', 'Chi0v', 'Chi1n', 'Chi1v', 'Kappa2']
qm7_7 = ['MaxPartialCharge', 'Chi0v', 'Chi1n', 'Chi1v', 'Kappa2', 'SlogP_VSA4', 'EState_VSA9']
qm7_10 = ['MaxPartialCharge', 'Chi0v', 'Chi1n', 'Chi1v', 'Kappa2', 'PEOE_VSA4', 'SlogP_VSA3', 'SlogP_VSA4', 'EState_VSA9', 'VSA_EState2']
qm7_20 = ['MaxPartialCharge', 'BCUT2D_MRLOW', 'Chi0v', 'Chi1n', 'Chi1v', 'Kappa2', 'PEOE_VSA11', 'PEOE_VSA4', 'SMR_VSA5', 'SlogP_VSA3', 'SlogP_VSA4', 'SlogP_VSA8', 'EState_VSA7', 'EState_VSA9', 'VSA_EState2', 'VSA_EState7', 'fr_NH1', 'fr_Ndealkylation1', 'fr_epoxide']

print(set(qm7_3), '\n')
print(set(qm7_5) - set(qm7_3), '\n')
print(set(qm7_7) - set(qm7_5), '\n')
print(set(qm7_10) - set(qm7_7), '\n')
print(set(qm7_20) - set(qm7_10))

{'Chi1n', 'Chi1v', 'Chi0v'} 

{'MaxPartialCharge', 'Kappa2'} 

{'SlogP_VSA4', 'EState_VSA9'} 

{'VSA_EState2', 'PEOE_VSA4', 'SlogP_VSA3'} 

{'BCUT2D_MRLOW', 'PEOE_VSA11', 'SlogP_VSA8', 'EState_VSA7', 'fr_Ndealkylation1', 'SMR_VSA5', 'fr_epoxide', 'fr_NH1', 'VSA_EState7'}


In [1]:
# qm9
qm9_3 = ['Chi0', 'Chi0v', 'HeavyAtomCount']
qm9_5 = ['Chi0', 'Chi0v', 'TPSA', 'HeavyAtomCount', 'fr_Al_OH']
qm9_7 = ['Chi0', 'Chi0v', 'Chi4v', 'TPSA', 'HeavyAtomCount', 'NumHAcceptors', 'fr_Al_OH']
qm9_10 = ['BCUT2D_CHGHI', 'Chi0', 'Chi0v', 'Chi4v', 'SMR_VSA9', 'TPSA', 'HeavyAtomCount', 'NumHAcceptors', 'NumRotatableBonds', 'fr_Al_OH']
qm9_20 = ['BCUT2D_CHGHI', 'BalabanJ', 'BertzCT', 'Chi0', 'Chi0v', 'Chi4v', 'Kappa1', 'PEOE_VSA4', 'SMR_VSA9', 'SlogP_VSA10', 'TPSA', 'VSA_EState4', 'VSA_EState7', 'HeavyAtomCount', 'NumHAcceptors', 'NumRotatableBonds', 'NumSaturatedCarbocycles', 'MolLogP', 'fr_Al_OH', 'fr_Ar_OH']

print(set(qm9_3), '\n')
print(set(qm9_5) - set(qm9_3), '\n')
print(set(qm9_7) - set(qm9_5), '\n')
print(set(qm9_10) - set(qm9_7), '\n')
print(set(qm9_20) - set(qm9_10))

{'HeavyAtomCount', 'Chi0', 'Chi0v'} 

{'TPSA', 'fr_Al_OH'} 

{'NumHAcceptors', 'Chi4v'} 

{'NumRotatableBonds', 'BCUT2D_CHGHI', 'SMR_VSA9'} 

{'BertzCT', 'PEOE_VSA4', 'Kappa1', 'NumSaturatedCarbocycles', 'MolLogP', 'BalabanJ', 'SlogP_VSA10', 'VSA_EState4', 'VSA_EState7', 'fr_Ar_OH'}


In [1]:
import torch

print("Is CUDA available:", torch.cuda.is_available())
print("CUDA device count:", torch.cuda.device_count())
print("CUDA device name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU detected")

Is CUDA available: True
CUDA device count: 1
CUDA device name: NVIDIA GeForce RTX 3070


In [2]:
import dgl
print("DGL version:", dgl.__version__)

c:\Programming\Anaconda\envs\egcn\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


DGL version: 2.2.1+cu121


In [4]:
print("torch version:", torch.__version__) # torch 버전
print("cuda version:", torch.version.cuda) # cuda 버전

print("Is CUDA available:", torch.cuda.is_available())
print("CUDA device count:", torch.cuda.device_count())
print("CUDA device name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU detected")

torch version: 2.1.0+cu121
cuda version: 12.1
Is CUDA available: True
CUDA device count: 1
CUDA device name: NVIDIA GeForce RTX 3070
